### ISSUE TITLE
jsonlog doesn't JSON-ify log_duration

### ISSUE THREAD

**Issue by davidfetter** [michaelpq/pg_plugins#12]
Steps to reproduce:

- Install jsonlog as instructed. (I did this with c45fb43c8448c5b710d4ef9774497e1789e070e5)
- ALTER SYSTEM SET log_duration = 'on';
- restart postgresql server
- watch logs for non-JSON lines.

**Comment by michaelpq** [comment]
Well, one can just do the following to block any further logs to be printed to the server logs:
edata->output_to_server = false;
However I am not sure that you'd want to do that in all cases, so having a custom boolean GUC to control that would be more useful. Want to write a patch?

**Comment by michaelpq** [comment]
Seeing no patches, I am closing that as I am not really willing to change the default behavior. I just gave the solution anyway, and this should be combined with DefineCustomBoolVariable using SIGHUP loaded by _PG_init() to have a dynamic switch.
