### ISSUE TITLE
Question and installation issues

### ISSUE THREAD

**Issue by sLuvpreet33** [michaelpq/pg_plugins#15]
I cloned it and ran `make install`, this is what happened,

    luvpreet@DHARI-Inspiron-3542:~/Desktop/pg_plugins$ make install
    You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application. 
    make: *** No rule to make target 'install'.  Stop.

I searched for this problem, after that, 

    luvpreet@DHARI-Inspiron-3542:~/Desktop/pg_plugins$ sudo apt-get install libpq-dev

After that, 

    luvpreet@DHARI-Inspiron-3542:~/Desktop/pg_plugins$ make install
    Makefile:5: /usr/lib/postgresql/9.6/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
    make: *** No rule to make target '/usr/lib/postgresql/9.6/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.

What is the issue coming in installation ? How do I solve it ? 

Question : Can it send JSON format logs to rsyslog. In one of the previous issues I read that we have to write some custom code for that. Have you made that change by default OR still now we had to write some custom code for that ?

**Comment by michaelpq** [comment]
> What is the issue coming in installation ? How do I solve it ?

No idea. This really depends only on your distribution. Are you sure that it is dropping in correctly all the files needed to compile an extension? Be careful that I maintain this code to only be compatible with the latest version of Postgres in development. You may need some extra effort to compile things on past versions. And I intend to keep the code simple for development purposes.

> Question : Can it send JSON format logs to rsyslog. In one of the previous issues I read that we have to write some custom code for that. Have you made that change by default OR still now we had to write some custom code for that ?

Yes, I think that you can do that by modifying jsonlog, and you will need to copy/paste a bit of code from upstream Postgres as the APIs of elog.c are only static :(
