### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jobinau** [michaelpq/pg_plugins#16]
I was going through your blog posts and code available here.
decoder_raw.c is an intersting project.

What is the possibility of a standalone tool like pg_xlogdump for WAL scanning, which can produce all logical statements?
I see that pg_xlogdump also using XLogReadRecord API for getting WAL records.

**Comment by michaelpq** [comment]
Looking only at the WAL records to produce logical data looks difficult to me. You need to have as well a look in the past to be able to rebuild logical records that could be part of long-running transactions (that's actually a reason why OldestXmin is kept up to date with logical replication slots which retain the largest amount of WAL). I am not sure of your use case, but did you look at pg_recvlogical?
