### ISSUE TITLE
Propose JSON logging upstream

### ISSUE THREAD

**Issue by blaggacao** [michaelpq/pg_plugins#24]
Now-a-days (ELK stacks and their likes), json or [logfmt](https://godoc.org/github.com/kr/logfmt) logging should be a standard option in every library.

Have you, by chance, checked the concordance with the above statement in upstream postgres?

**Comment by michaelpq** [comment]
I proposed that a couple of years back, to be rejected as the key names are too much repetitive and take too much place. I have personally plans to work on other things, so if anybody wishes to take this code and send a proposal upstream, feel free to! The code is under PostgreSQL license and I am fine if a patch is proposed even with this code taken.

**Comment by blaggacao** [comment]
I've never contributed to postgres, so would this be taking jsonlog and copy it in https://github.com/postgres/postgres/tree/master/contrib with accompanying discussion on https://www.postgresql.org/list/pgsql-hackers/?

**Comment by blaggacao** [comment]
Let's see: https://www.postgresql.org/message-id/CAH6vsWLM4tD_jUEPQvihraMReBfr%2BgN%2Br_-GdPgbVvjuZZQBCg%40mail.gmail.com

**Comment by michaelpq** [comment]
Let's discuss that on the community mailing lists if there is need.
