### ISSUE TITLE
Error with 'jsonlog' on Centos-7

### ISSUE THREAD

**Issue by sergiospa** [michaelpq/pg_plugins#29]
Hi again!

Last Friday, I managed to get `jsonlog` extension working on an Ubuntu-19.04. The thing is, I have tried the same on a Centos-7 but when I try to restart the service with `systemctl restart postgresql-9.6.service`, I get the following error:
`FATAL:  could not access file "jsonlog": No such file or directory`

These are all the steps I followed to install Postgres + jsonlog extension:
```
• Install the repository RPM:
# yum install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

• Install the package: 
# yum install postgresql96

• Install the server packages:
# yum install postgresql96-server

• Install the devel package:
# yum install postgresql-devel

• Add `pg_config` to your PATH:
# export PATH=$PATH:/usr/pgsql-9.6/bin/
 
• Create a directory to store jsonlog source code:
# mkdir jsonlog

• Put there the files `Makefile` and `jsonlog.c`.
• Compile `jsonlog`
- Make sure GCC (GNU Compiler Collection) is installed, which is necessary to compile C:
# yum install gcc
- Install the required dependencies:
# yum install openssl-devel
- Compile:
# make
# make install

• Add the following changes in the configuration file `/var/lib/pgsql/9.6/data/postgresql.conf`:
shared_preload_libraries = 'jsonlog' 
log_min_messages = info
log_connections = on
log_disconnections = on
log_statement = 'all'
```
I'm going to try it again from zero, but I would really appreciate some help!
Regards,
Sergio.

**Comment by sergiospa** [comment]
Still can't make it. Is there any specific directory where I should compile the source code or place something?

**Comment by sergiospa** [comment]
I moved `jsonlog.so` to `/usr/pgsql-9.6/lib/`, where the libraries are meant to be stored, and got the following new error:
```
Nov 18 15:44:28 centos-7-20 postmaster[15194]: < 2019-11-18 15:44:28.992 UTC > FATAL:  incompatible library "/usr/pgsql-9.6/lib/jsonlog.so": version mismatch
Nov 18 15:44:28 centos-7-20 postmaster[15194]: < 2019-11-18 15:44:28.992 UTC > DETAIL:  Server is version 9.6, library is version 9.2.
```
How is this possible? I installed the same versions for everything in an Ubuntu and it worked :S

**Comment by michaelpq** [comment]
Well, I still don't see any bugs in the way the code is built. My best advice is that you should carefully review your packaing, but FWIW this error means that you compiled the version based on Postgres 9.2, and you are trying to load it on a 9.6 server. So your compilation step is in my opinion wrong.

**Comment by sergiospa** [comment]
@michaelpq Thanks a lot, I appreciate your response. I just followed the steps above in a new Centos 7 box. Do you see any wrong step there? :/
Regards,
Sergio.

**Comment by michaelpq** [comment]
I can see two things:
1) postgresql-devel does not correspond to 9.6
2) You need to update your PATH as follows so as you drag the 9.6 binaries *before* the rest:
export PATH=/usr/pgsql-9.6/bin/:$PATH

**Comment by sergiospa** [comment]
Thanks again for the response, I will try this tomorrow.
I appreciate your help.

Regards,
Sergio.
