### ISSUE TITLE
Newbie here - getting error on PasswordType

### ISSUE THREAD

**Issue by auramuccio** [michaelpq/pg_plugins#30]
Hi - 

Running on RHEL7 with EDB PG 9.6 and I have downloaded just the "passwordcheck_extra" package to the contrib folder. My pg_contrib command is in /usr/edb/as9.6/bin/pg_config and I confirmed that /usr/edb/as9.6/bin is in the $PATH for the root user (which I am running the commands as). Originally I was getting an error that stated fatal error: common/md5.h. So I changed common/md5.h to libpq/md5.h in the passwordcheck_extra.c. So now I run the following: 

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -I/usr/libexec/icu-edb53.1/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -I/usr/include/et -fPIC -I. -I./ -I/usr/edb/as9.6/include/server -I/usr/edb/as9.6/include/internal -I/usr/include/et -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/libexec/icu-edb53.1/include   -I/usr/include  -c -o passwordcheck_extra.o passwordcheck_extra.c
passwordcheck_extra.c:70:7: error: unknown type name ‘PasswordType’

I'm not sure why it can't find the PasswordType data type. We currently have the passwordcheck library loaded and it used the same datatype.  

Any advice would be greatly appreciated.

**Comment by michaelpq** [comment]
The code of this tree is only kept compatible with the latest version of PostgreSQL (aka the master branch). That's mentioned in the README:
```
In all cases each plugin is maintained to be compatible with the latest version of PostgreSQL.
```
In this case you can adapt the code easily, see what has been done to upstream's passwordcheck when PasswordType got introduced:
https://github.com/postgres/postgres/commit/dbd69118c05d73969a1bd52ead6702c6e40b0fee
You just need to make the code come back to something similar.

**Comment by auramuccio** [comment]
I'm very new to PostgreSQL - so that didn't even occur to me to check that. Thank you so much for your response!!
