### ISSUE TITLE
macOS instructions

### ISSUE THREAD

**Issue by fabiog1901** [michaelpq/pg_plugins#35]
Hi Michael,

I'm trying to get JSON logging working in my PGSQL homebrew installation on my macbook. I'm afraid i'm not a developer so I'm not too familiar with the compile process. Would you mind sharing some simple instructions? I bet that will help a lot of people start using your jsonlog plugin!

Thank you

**Comment by michaelpq** [comment]
Sure. I don't use homebrew directly for the base builds of the modules I use with PostgreSQL, but assuming that this installs all the tools needed by the contrib modules, with mainly pgxs.mk present, then you only need to have pg_config in your environment's PATH for the version of PostgreSQL you are trying to build the module with. Once this is done, a simple make command from the path of the module should allow you to build it, and make install should install it. You may likely need extra permissions to install new so objects there, and I don't know how brew would react to that.
