### ISSUE TITLE
Fatal Error While Compiling Process passwordcheck_extra

### ISSUE THREAD

**Issue by nitz1990-hash** [michaelpq/pg_plugins#37]
Hello Michael,

Appreciate your work in passwordcheck_extra. 

We are facing fatal error: common/md5.h: No such file or directory while running make install command. 

We are using PostgreSQL Version 9.5.

Kindly help us to resolve this.

**Comment by michaelpq** [comment]
As of the README, only the master branch of PostgreSQL is supported.

**Comment by nitz1990-hash** [comment]
Hello Michael,

So which module we should use for the PostgreSQL 9.5  and 9.6 version for password complexity, 

Kindly guide us.

**Comment by michaelpq** [comment]
It is fine to grab this code and adjust it slightly for your needs.

**Comment by nitz1990-hash** [comment]
Hello Michael,

Thanks for your help.
