### ISSUE TITLE
Timestamp of transactions

### ISSUE THREAD

**Issue by stedliu** [michaelpq/pg_plugins#38]
Hello,

Is it possible to get transaction timestamp that associates with each lsn, xid, and DML statements when using decoder_raw via pg_recvlogical or SQL interface?

Below is the error when using decoder_raw plugin:

testdb=> SELECT * FROM pg_logical_slot_peek_changes('test_slot', NULL, NULL,'include-timestamp', 'on');
ERROR:  option "include-timestamp" = "on" is unknown
CONTEXT:  slot "test_slot", output plugin "decoder_raw", in the startup callback

Below is the result when using test_decoding:

testdb=> SELECT * FROM pg_logical_slot_peek_changes('regression_slot', NULL, NULL, 'include-timestamp', 'on');
     lsn      |  xid   |                                  data
--------------+--------+------------------------------------------------------------------------
 525/980009D8 | 140614 | BEGIN 140614
 525/980009D8 | 140614 | table public.test: INSERT: id[bigint]:1 name[character varying]:'TST1'
 525/98000AF0 | 140614 | COMMIT 140614 (at 2021-06-07 19:45:41.947602+00)
 525/98000AF0 | 140615 | BEGIN 140615
 525/98000AF0 | 140615 | table public.test: INSERT: id[bigint]:2 name[character varying]:'TST2'
 525/98000B68 | 140615 | COMMIT 140615 (at 2021-06-07 19:45:48.623761+00)
(6 rows)

Thank you in advance.

Ted

**Comment by michaelpq** [comment]
decoder_raw does not support this option, but it would be possible to support it. The only thing that's needed is a patch that could be merged and I have no plans to work on that myself, but any patches are welcome.
