### ISSUE TITLE
Index access method blackhole

### ISSUE THREAD

**Issue by ccleve** [michaelpq/pg_plugins#39]
Michael,

Your table access method blackhole code is really useful. I got it working quickly and have used it for experimentation.

I'm looking to implement a index access method, though, and it's slow going, because I don't fully understand the relationship between the access method, operators, and operator classes. The documentation is opaque, to say the least.

Do you have any interest in creating a blackhole index access method that demonstrates the basic syntax and functionality?

**Comment by michaelpq** [comment]
I have committed something like that directly in the upstream PostgreSQL code: look at src/test/modules/dummy_index_am/ as of the top of the master branch. The thing is not perfect, and it could be improved, still that offers a good starting point.
