### ISSUE TITLE
Unquoted boolean in decoder_raw

### ISSUE THREAD

**Issue by pslavov** [michaelpq/pg_plugins#4]
Hi,
I am using your plug-in about logical decoding, and I noticed that in the insert and update statements boolean values are not quoted. That results in failure when I try to run the statements.
I removed the boolean case from the function print_literal and now they are quoted correctly.
Is there a reason not the quote boolean values?

**Comment by michaelpq** [comment]
Yes, I was obviously lazy here. I fixed that with 029a273, representing the values as "true" and "false", without quotes.
