### ISSUE TITLE
Last passwordcheck_extra only for PostgreSQL 15?

### ISSUE THREAD

**Issue by branecc** [michaelpq/pg_plugins#41]
I'm trying to compile passwordcheck_extra extension on CentOS 7.9 and PostgreSQL 11. I got errors:

$ make USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o passwordcheck_extra.o passwordcheck_extra.c
passwordcheck_extra.c: In function ‘check_password’:
passwordcheck_extra.c:93:4: error: too many arguments to function ‘pg_md5_encrypt’
    if (!pg_md5_encrypt(username, username, namelen, encrypted, &errstr))
    ^
In file included from passwordcheck_extra.c:24:0:
/usr/pgsql-11/include/server/common/md5.h:24:13: note: declared here
 extern bool pg_md5_encrypt(const char *passwd, const char *salt,
             ^
passwordcheck_extra.c: In function ‘passwordcheck_extra_load_params’:
passwordcheck_extra.c:285:2: warning: implicit declaration of function ‘MarkGUCPrefixReserved’ [-Wimplicit-function-declaration]
  MarkGUCPrefixReserved("passwordcheck_extra");
  ^
make: *** [passwordcheck_extra.o] Error 1

Checked sources for PG_11 and PG_15 in guc.h. Function MarkGUCPrefixReserved() exists only in PG_15.
For pg_md5_encrypt() there is wrong signature in md5.h (at least for PG_11).

**Comment by michaelpq** [comment]
As of https://github.com/michaelpq/pg_plugins/blob/main/README:
```
In all cases each plugin is maintained to be compatible with the latest version of PostgreSQL.
```
