### ISSUE TITLE
passwordcheck_extra not successfully compile

### ISSUE THREAD

**Issue by arezvani** [michaelpq/pg_plugins#43]
Hi,
I get this warning when I want to compile passwordcheck_extra:
implicit declaration of function ‘MarkGUCPrefixReserved’

Can you help me please?

also I have error for passwordcheck_extra.c:93:9: error: too many arguments to function ‘pg_md5_encrypt’
    if (!pg_md5_encrypt(username, username, namelen, encrypted, &errstr))
    
so I delete that lines.

**Comment by michaelpq** [comment]
Well, you are trying to compile the module with a version that has no support for it, and the README of the project documents this choice:
```In all cases each plugin is maintained to be compatible with the latest version of PostgreSQL.```
This module needs to be modified to work properly with the version of PostgreSQL you are trying to build with. You can check the output of "pg_config --version" to get this information, for example, in your PATH.

**Comment by arezvani** [comment]
I use postgres 14.5
