### ISSUE TITLE
Validation of installation

### ISSUE THREAD

**Issue by PatrickNa** [michaelpq/pg_plugins#48]
I spend a lot of time with the process of installing the `passwordcheck_extra` extension. It turns out that it was available right after running the commands and extending the _postgresql.conf_ by the line as described in the README.md file. 

As someone inexperienced with PostgreSQL extensions I could not when the extensions is available in the database of my choice. Reasons are:

1. The official documentation of PostgreSQL includes the step of `CREATE EXTENSION extension_name`. This however is not required in the installation of the `passwordcheck_extra` extension.
2. Even after installation, the extension is not show in the `pg_extension` table. 

I finally figured it out by running a `CREATE ROLE` command of the test file in the target database and running into a "password too short" notification. I got the functionality that I was looking for! Thank you for that! 

Based on my experience I think it would be beneficial to add a few more information to the README.md file and explain what can be expected after running the instructions. If I could tag this issue, I would give it a `nice-to-have` rather than a `bug`.

Regards

**Comment by michaelpq** [comment]
This module does not require CREATE EXTENSION to work, just to be loaded in the backend. So you can run a LOAD command to check its validity. However, as this is really something you'd want to enable at cluster level, LOAD is not something I see recommending, so the current README telling only about shared_preload_libraries is more than enough IMO.

If you think that this could be improved, feel free to send a patch!
