### ISSUE TITLE
decoder_raw fail while performing pg_logical_slot_peek_changes

### ISSUE THREAD

**Issue by jkoptimize** [michaelpq/pg_plugins#50]
I used decode_raw plugin with Postgresql12, the platform is centos 8.2. A segmentation fault occurs when the basic regression test case is executed:

postgres=# SELECT data FROM pg_logical_slot_peek_changes('custom_slot', NULL, NULL);
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> \q

I then used gdb to debug and found that the heap_getattr call in line 454 of the source code was abnormal, and the input HeapTuple was an illegal value (but not NULL) 0x8. This phenomenon was very strange, and I did not know why this weird value was returned.

**Comment by michaelpq** [comment]
The regression test suite works with PostgreSQL compiled at the top of the master branch, which is the amount of compatibility I'm aiming at keeping for this template (see README of the project), and it works correctly here.

If you still an issue, more information would be required, at least with:
- Version of PostgreSQL involved.
- Backtrace.
