### ISSUE TITLE
passwordcheck_extra  can't be built with clang version >= 17

### ISSUE THREAD

**Issue by gsl23** [michaelpq/pg_plugins#52]
Hi Michael ! Big thx for very your useful tool passwordcheck_extra , but unfortunally,  it can't be built with clang version >= 17

# make install
...
/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -Xclang -no-opaque-pointers -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-deprecated-non-prototype -O2  -I. -I./ -I/usr/pgsql-15/include/server -I/usr/pgsql-15/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o passwordcheck_extra.bc passwordcheck_extra.c
error: unknown argument: '-no-opaque-pointers'
make: *** [/usr/pgsql-15/lib/pgxs/src/makefiles/../../src/Makefile.global:1081: passwordcheck_extra.bc] Error 1  )

PS. Ok with clang ver = 16

**Comment by michaelpq** [comment]
>  error: unknown argument: '-no-opaque-pointers'
Your build of PostgreSQL has the control of the compiler switches that get pulled to an extension compile command, not this module.
