### ISSUE TITLE
jsonlog does not preserve the emit_log_hook

### ISSUE THREAD

**Issue by eremmel** [michaelpq/pg_plugins#6]
First of all thanks for your nice code. It gave me the quick route to make my own (first) plugin within 4 hours!
Your plugin is an end point for it takes over the writing of the log. But when other plugins hooked up before this one I think it is good that you give them the opportunity to run and check  their result (edate->output_to_server) before flushing.

**Comment by michaelpq** [comment]
This doesn't sound like a bad idea, so done with d3c7bbe.
